[project]
name = "crawler-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crawl4ai>=0.7.7",
    "ipykernel>=7.1.0",
<<<<<<< HEAD
    "pandas>=2.3.3",
=======
    "nest-asyncio>=1.6.0",
>>>>>>> ae98d9f0a5e73c1c9f9fe5cc1d01891a26788908
    "playwright>=1.56.0",
    "streamlit>=1.52.1",
]
